# -*- coding: utf-8 -*-
"""ML_Task_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QovbYaEEgMntcRD2Tm5D6hcQbqRoZHfb
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt

df=pd.read_csv("/content/UpdatedResumeDataSet.csv")

df.head()

df.columns

df.isnull().sum()

df['Resume'][0][:1000]

import re
def clean_text(text):
  text=text.lower()
  text=re.sub(r'http\S+',' ',text)
  text=re.sub(r'[^a-zA-Z]',' ',text)
  text=re.sub(r'\s+',' ',text)
  return text.strip()
df['Clean_Resume']=df['Resume'].apply(clean_text)

df.head()

skills=[
    'python','java','sql','machine learning','deep learning','data analysis','power bi','excel','tensorflow','pytorch','aws','docker','git','communication'
]

def extract_skills(text):
  found_skills=[]
  for skill in skills:
    if skill in text:
      found_skills.append(skill)
  return found_skills
df['Skills']=df['Clean_Resume'].apply(extract_skills)

df[['Category','Skills']].head(10)

job_description="""
    We are hiring an AI/ML Engineer.
    Required Skills:
    Python Machine Learning Deep Learning SQL AWS
    """

cleaned_job_description = clean_text(job_description)
job_description = cleaned_job_description
job_description

required_skills=extract_skills(job_description)
required_skills

'python' in job_description

scores=[]
for resume in df['Clean_Resume']:
  vectorizer=TfidfVectorizer()
  tfidf=vectorizer.fit_transform([job_description,resume])
  similarity=cosine_similarity(tfidf[0:1],tfidf[1:2])[0][0]
  scores.append(similarity)

df['Scores']=scores
df[['Category','Scores']].head(10)

ranked_df=df.sort_values(by='Scores',ascending=False)
ranked_df[['Category','Scores']].head(10)

def skill_gap(candidate_skills,required_skills):
  candidate_skills=set(candidate_skills)
  required_skills=set(required_skills)
  gap=required_skills-candidate_skills
  return list(gap)

df['missing_skills']=df['Skills'].apply(lambda x:skill_gap(x,required_skills))

best_candidate=ranked_df.iloc[0]
best_candidate

df['Score_percent']=(df['Scores']*100).round(2)

ranked_df=df.sort_values(by='Score_percent',ascending=False)
ranked_df[['Category','Score_percent']].head(10)

import matplotlib.pyplot as plt
  top10 = ranked_df.head(10)
  plt.figure(figsize=(10,6))
  plt.bar(
      range(len(top10)),
      top10['Score_percent']
  )
  plt.xticks(
      range(len(top10)),
      top10['Category'],
      rotation=45
  )
  plt.ylabel("Match Score(%)")
  plt.xlabel("Candidates Category")
  plt.title("Top 10 Ranked Candidates")
  plt.show()

job_descriptions = {

    "AI_ML_Engineer":
    """
    Python Machine Learning Deep Learning SQL AWS
    """,

    "Data_Scientist":
    """
    Python Machine Learning Statistics SQL Deep Learning
    """,

    "Data_Analyst":
    """
    SQL Excel Power BI Data Analysis Statistics
    """,

    "Java_Developer":
    """
    Java Spring Boot MySQL Git
    """,

    "Python_Developer":
    """
    Python Django Flask SQL Git
    """
}

selected_role = "Data_Scientist"

job_description = clean_text(
    job_descriptions[selected_role]
)

required_skills = extract_skills(
    job_description
)

scores = []

for resume in df['Clean_Resume']:

    vectorizer = TfidfVectorizer()

    tfidf = vectorizer.fit_transform(
        [job_description, resume]
    )

    similarity = cosine_similarity(
        tfidf[0:1],
        tfidf[1:2]
    )[0][0]

    scores.append(similarity)

df['score_percent'] = (
    np.array(scores) * 100
).round(2)

ranked_df = df.sort_values(
    by='score_percent',
    ascending=False
)

ranked_df.head(10)

ranked_df.to_csv('candidate_ranking_results.csv', index=False)

import os
os.listdir()

from google.colab import files
files.download("candidate_ranking_results.csv")